### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by fhinkel** [knaufk/BlitzPay_Frontend#9]
We need a footer with a little bit of information about who we are.

**Comment by knaufk** [comment]
I have added a sentence "maintained by TNG..." with link to our impressum in the footer. Anything else?

**Comment by fhinkel** [comment]
Add "Beta" to footer

**Comment by fhinkel** [comment]
Link to GitHub to show that it's in active development

**Comment by knaufk** [comment]
Done. I used the grunt-string-replace plugin, which needed some changes in the webpack.config. Unfortunately everything is now first copied from src/ to dest/ and then packed from there. Probably we can do this simpler. Franzi you worked on the webpack config at the Hackathon, maybe you can have a look at it.

**Comment by mkreidenweis** [comment]
Last night when demoing the app to somebody I noticed that when my device is showing the keyboard, then the footer moves to the same place as the Login button, apparently with a higher z-index. So it's hard to hit the Login button and you click the link in the footer instead. This needs some improvement.
